### YamlMime:ManagedReference
items:
- uid: System.Activities.Statements.Catch
  id: Catch
  children:
  - System.Activities.Statements.Catch.ExceptionType
  langs:
  - csharp
  name: Catch
  nameWithType: Catch
  fullName: System.Activities.Statements.Catch
  type: Class
  summary: "対応する例外がスローされた後に実行するアクションを含む<xref uid=&quot;langword_csharp_Try&quot; name=&quot;Try&quot; href=&quot;&quot;></xref>のブロック、<xref:System.Activities.Statements.TryCatchFinally>アクティビティです</xref:System.Activities.Statements.TryCatchFinally>。"
  remarks: "デザイナーで格納されると、Catch アクティビティをデザイナーで並べ替えることができません。  Catch アクティビティのコレクションを並べ替えるを削除、正しい順序で追加し直すか、ワークフローの xaml (コード) ビューを使用します。"
  syntax:
    content: public abstract class Catch
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.Statements.Catch.ExceptionType
  id: ExceptionType
  parent: System.Activities.Statements.Catch
  langs:
  - csharp
  name: ExceptionType
  nameWithType: Catch.ExceptionType
  fullName: System.Activities.Statements.Catch.ExceptionType
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities.Statements
  summary: "例外の種類を<xref href=&quot;System.Activities.Statements.Catch&quot;></xref>ブロックが処理されます。"
  syntax:
    content: public abstract Type ExceptionType { get; }
    return:
      type: System.Type
      description: "例外の種類。"
  overload: System.Activities.Statements.Catch.ExceptionType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Activities.Statements.Catch.ExceptionType
  parent: System.Activities.Statements.Catch
  isExternal: false
  name: ExceptionType
  nameWithType: Catch.ExceptionType
  fullName: System.Activities.Statements.Catch.ExceptionType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Activities.Statements.Catch.ExceptionType*
  parent: System.Activities.Statements.Catch
  isExternal: false
  name: ExceptionType
  nameWithType: Catch.ExceptionType
