### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationAbortedEventArgs
  id: WorkflowApplicationAbortedEventArgs
  children:
  - System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  langs:
  - csharp
  name: WorkflowApplicationAbortedEventArgs
  nameWithType: WorkflowApplicationAbortedEventArgs
  fullName: System.Activities.WorkflowApplicationAbortedEventArgs
  type: Class
  summary: "中止されたワークフロー インスタンスに関するデータを提供します。"
  remarks: "ワークフローがによってホストされている場合、<xref:System.Activities.WorkflowApplication>を中止すると、<xref:System.Activities.WorkflowApplication.Aborted%2A>ハンドラーが呼び出されますと<xref:System.Activities.WorkflowApplication.Completed%2A>ハンドラーは呼び出されません</xref:System.Activities.WorkflowApplication.Completed%2A></xref:System.Activities.WorkflowApplication.Aborted%2A></xref:System.Activities.WorkflowApplication>。"
  example:
  - "The following code example inspects the WorkflowApplicationAbortedEventArgs passed into the <xref:System.Activities.WorkflowApplication.Aborted%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about why workflow was aborted.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#5](~/add/codesnippet/csharp/t-system.activities.work_4_1.cs)]"
  syntax:
    content: 'public class WorkflowApplicationAbortedEventArgs : System.Activities.WorkflowApplicationEventArgs'
  inheritance:
  - System.EventArgs
  - System.Activities.WorkflowApplicationEventArgs
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  id: Reason
  parent: System.Activities.WorkflowApplicationAbortedEventArgs
  langs:
  - csharp
  name: Reason
  nameWithType: WorkflowApplicationAbortedEventArgs.Reason
  fullName: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "ワークフロー インスタンスが中止された理由に関する情報を提供する例外を取得します。"
  remarks: "ワークフローがによってホストされている場合、<xref:System.Activities.WorkflowApplication>を中止すると、<xref:System.Activities.WorkflowApplication.Aborted%2A>ハンドラーが呼び出されますと<xref:System.Activities.WorkflowApplication.Completed%2A>ハンドラーは呼び出されません</xref:System.Activities.WorkflowApplication.Completed%2A></xref:System.Activities.WorkflowApplication.Aborted%2A></xref:System.Activities.WorkflowApplication>。"
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationAbortedEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Aborted%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays information about why workflow was aborted.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#5](~/add/codesnippet/csharp/p-system.activities.work_6_1.cs)]"
  syntax:
    content: public Exception Reason { get; }
    return:
      type: System.Exception
      description: "ワークフロー インスタンスが中止された理由に関する情報を提供する例外。"
  overload: System.Activities.WorkflowApplicationAbortedEventArgs.Reason*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: System.Activities.WorkflowApplicationEventArgs
- uid: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
  parent: System.Activities.WorkflowApplicationAbortedEventArgs
  isExternal: false
  name: Reason
  nameWithType: WorkflowApplicationAbortedEventArgs.Reason
  fullName: System.Activities.WorkflowApplicationAbortedEventArgs.Reason
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationAbortedEventArgs.Reason*
  parent: System.Activities.WorkflowApplicationAbortedEventArgs
  isExternal: false
  name: Reason
  nameWithType: WorkflowApplicationAbortedEventArgs.Reason
