### YamlMime:ManagedReference
items:
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  id: WorkflowTerminatedEventArgs
  children:
  - System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  langs:
  - csharp
  name: WorkflowTerminatedEventArgs
  nameWithType: WorkflowTerminatedEventArgs
  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  type: Class
  summary: "データを提供、 <xref href=&quot;System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated&quot;> </xref>イベント。"
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]3 つの方法のいずれかで、ワークフロー インスタンスを終了する可能性がありますホストを呼び出すことが<xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>、<xref:System.Workflow.ComponentModel.TerminateActivity>アクティビティは、ワークフロー インスタンスの内部から呼び出すことがありますまたはワークフロー ランタイム エンジンはハンドルされない例外のため、インスタンスを終了する可能性があります。</xref:System.Workflow.ComponentModel.TerminateActivity> </xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName> 。 ワークフロー インスタンスが終了すると、ワークフロー ランタイム エンジンを発生させます、<xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>イベント</xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>。 <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>。</xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>イベント ハンドラーを追加することでこのイベントを定期受信ホスト"
  example:
  - "The following code example demonstrates an event handler method that takes WorkflowTerminatedEventArgs as a parameter. The `OnWorkflowTerminated` method is called when the <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated> event is raised. The code uses the <xref:System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception%2A> property get the message associated with the exception that caused the workflow to terminate.  \n  \n This code example is part of the Sequential Workflow with Parameters SDK Sample from the Program.cs file. For more information, see [Sequential Workflow with Parameters](http://msdn.microsoft.com/en-us/17157f2d-8fed-4848-a386-e4efa381b66b).  \n  \n [!code-cs[WF_Samples#193](~/add/codesnippet/csharp/wf_snippets/snippets19.cs#193)]\n [!code-vb[WF_Samples#193](~/add/codesnippet/visualbasic/wf_snippets/snippets19.vb#193)]"
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public class WorkflowTerminatedEventArgs : System.Workflow.Runtime.WorkflowEventArgs
  inheritance:
  - System.EventArgs
  - System.Workflow.Runtime.WorkflowEventArgs
  implements: []
  inheritedMembers:
  - System.Workflow.Runtime.WorkflowEventArgs.WorkflowInstance
  platform:
  - net462
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  id: Exception
  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  langs:
  - csharp
  name: Exception
  nameWithType: WorkflowTerminatedEventArgs.Exception
  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime
  summary: "ワークフロー インスタンスの終了の原因となった例外を取得します。"
  remarks: "ワークフロー インスタンスが終了すると、ハンドルされない例外のため、例外には、未処理の例外が含まれています。       ホストが呼び出したワークフロー インスタンスを終了するときに<xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>か、または、<xref:System.Workflow.ComponentModel.TerminateActivity>アクティビティ、例外が含まれています、<xref:System.Workflow.ComponentModel.WorkflowTerminatedException>を持つその<xref:System.Exception.Message%2A>プロパティは終了の理由の説明を設定します</xref:System.Exception.Message%2A></xref:System.Workflow.ComponentModel.WorkflowTerminatedException></xref:System.Workflow.ComponentModel.TerminateActivity></xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>。 この説明を提供、ホストは、ワークフロー インスタンスを終了する場合、 `string` <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName></xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>パラメーター。 <xref:System.Workflow.ComponentModel.TerminateActivity>説明は<xref:System.Workflow.ComponentModel.TerminateActivity.Error%2A?displayProperty=fullName>。</xref:System.Workflow.ComponentModel.TerminateActivity.Error%2A?displayProperty=fullName>によって提供される、</xref:System.Workflow.ComponentModel.TerminateActivity>によって、ワークフロー インスタンスが終了した場合      > [!NOTE] > の場合、<xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>未処理の例外の原因ではないイベント、ワークフロー ランタイム エンジンをカプセル化の終了の理由の説明、<xref:System.Exception.Message%2A>のプロパティ、 <xref:System.Workflow.ComponentModel.WorkflowTerminatedException>、この例外を必ずしもスローされません</xref:System.Workflow.ComponentModel.WorkflowTerminatedException></xref:System.Exception.Message%2A></xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>。"
  example:
  - "The following code example demonstrates how you can use the Exception property to obtain information about an exception that caused a workflow to terminate. The `OnWorkflowTerminated` method takes a <xref:System.Workflow.Runtime.WorkflowTerminatedEventArgs> as a parameter. This method is called when the <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated> event is raised. The code uses the Exception property get the message associated with the exception that caused the workflow to terminate.  \n  \n This code example is part of the Sequential Workflow with Parameters SDK Sample from the Program.cs file. For more information, see [Sequential Workflow with Parameters](http://msdn.microsoft.com/en-us/17157f2d-8fed-4848-a386-e4efa381b66b).  \n  \n [!code-cs[WF_Samples#193](~/add/codesnippet/csharp/wf_snippets/snippets19.cs#193)]\n [!code-vb[WF_Samples#193](~/add/codesnippet/visualbasic/wf_snippets/snippets19.vb#193)]"
  syntax:
    content: public Exception Exception { get; }
    return:
      type: System.Exception
      description: "<xref:System.Exception>ワークフロー インスタンスの終了の原因となった</xref:System.Exception>。"
  overload: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Workflow.Runtime.WorkflowEventArgs
  isExternal: false
  name: System.Workflow.Runtime.WorkflowEventArgs
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  isExternal: false
  name: Exception
  nameWithType: WorkflowTerminatedEventArgs.Exception
  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception*
  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  isExternal: false
  name: Exception
  nameWithType: WorkflowTerminatedEventArgs.Exception
