### YamlMime:ManagedReference
items:
- uid: System.Diagnostics.Contracts.Internal.ContractHelper
  id: ContractHelper
  children:
  - System.Diagnostics.Contracts.Internal.ContractHelper.RaiseContractFailedEvent(System.Diagnostics.Contracts.ContractFailureKind,System.String,System.String,System.Exception)
  - System.Diagnostics.Contracts.Internal.ContractHelper.TriggerFailure(System.Diagnostics.Contracts.ContractFailureKind,System.String,System.String,System.String,System.Exception)
  langs:
  - csharp
  name: ContractHelper
  nameWithType: ContractHelper
  fullName: System.Diagnostics.Contracts.Internal.ContractHelper
  type: Class
  summary: "バイナリ リライターがコントラクト エラーの処理に使用するメソッドを提供します。"
  syntax:
    content: >-
      [System.Obsolete("Use the ContractHelper class in the System.Runtime.CompilerServices namespace instead.")]

      public static class ContractHelper
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Diagnostics.Contracts.Internal.ContractHelper.RaiseContractFailedEvent(System.Diagnostics.Contracts.ContractFailureKind,System.String,System.String,System.Exception)
  id: RaiseContractFailedEvent(System.Diagnostics.Contracts.ContractFailureKind,System.String,System.String,System.Exception)
  parent: System.Diagnostics.Contracts.Internal.ContractHelper
  langs:
  - csharp
  name: RaiseContractFailedEvent(ContractFailureKind,String,String,Exception)
  nameWithType: ContractHelper.RaiseContractFailedEvent(ContractFailureKind,String,String,Exception)
  fullName: System.Diagnostics.Contracts.Internal.ContractHelper.RaiseContractFailedEvent(ContractFailureKind,String,String,Exception)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Contracts.Internal
  summary: "バイナリ リライターが既定のエラー動作をアクティブ化するために使用します。"
  remarks: "バイナリ リライターがコントラクト エラー リスナーに通知するには、このメソッドを呼び出します。 RaiseContractFailedEvent メソッドがエラー時の動作 (アサートまたは throw) を実行していない自体です。 メソッドを返しますのかどうか、エラーは、リスナーによって処理、`null`です。 リスナーによって、エラーが処理されない場合は、ローカライズされたエラー メッセージが返されます。"
  syntax:
    content: public static string RaiseContractFailedEvent (System.Diagnostics.Contracts.ContractFailureKind failureKind, string userMessage, string conditionText, Exception innerException);
    parameters:
    - id: failureKind
      type: System.Diagnostics.Contracts.ContractFailureKind
      description: "エラーの種類。"
    - id: userMessage
      type: System.String
      description: "追加のユーザー情報。"
    - id: conditionText
      type: System.String
      description: "エラーの原因となった状態の説明。"
    - id: innerException
      type: System.Exception
      description: "現在の例外の原因となった内部例外。"
    return:
      type: System.String
      description: "Null 参照 (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> Visual Basic で) 場合は、イベントが処理されていて障害; をトリガーする必要がありますが、ローカライズされたエラー メッセージをそれ以外の場合を返します。"
  overload: System.Diagnostics.Contracts.Internal.ContractHelper.RaiseContractFailedEvent*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>failureKind</code>有効ではありません<xref:System.Diagnostics.Contracts.ContractFailureKind>値。"
  platform:
  - net462
- uid: System.Diagnostics.Contracts.Internal.ContractHelper.TriggerFailure(System.Diagnostics.Contracts.ContractFailureKind,System.String,System.String,System.String,System.Exception)
  id: TriggerFailure(System.Diagnostics.Contracts.ContractFailureKind,System.String,System.String,System.String,System.Exception)
  parent: System.Diagnostics.Contracts.Internal.ContractHelper
  langs:
  - csharp
  name: TriggerFailure(ContractFailureKind,String,String,String,Exception)
  nameWithType: ContractHelper.TriggerFailure(ContractFailureKind,String,String,String,Exception)
  fullName: System.Diagnostics.Contracts.Internal.ContractHelper.TriggerFailure(ContractFailureKind,String,String,String,Exception)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Diagnostics.Contracts.Internal
  summary: "既定のエラー動作をトリガーします。"
  remarks: "既定のエラー動作をさせるは、 <xref:System.Diagnostics.Debug.Assert%2A>、これにより、 **Assert**  ダイアログ ボックスを表示します</xref:System.Diagnostics.Debug.Assert%2A>。 スローするには、その動作を変更することができます、 <xref:System.Exception> ダイアログ ボックスを表示する代わりにします</xref:System.Exception>。"
  syntax:
    content: public static void TriggerFailure (System.Diagnostics.Contracts.ContractFailureKind kind, string displayMessage, string userMessage, string conditionText, Exception innerException);
    parameters:
    - id: kind
      type: System.Diagnostics.Contracts.ContractFailureKind
      description: "エラーの種類。"
    - id: displayMessage
      type: System.String
      description: "表示するメッセージ。"
    - id: userMessage
      type: System.String
      description: "追加のユーザー情報。"
    - id: conditionText
      type: System.String
      description: "エラーの原因となった状態の説明。"
    - id: innerException
      type: System.Exception
      description: "現在の例外の原因となった内部例外。"
  overload: System.Diagnostics.Contracts.Internal.ContractHelper.TriggerFailure*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Diagnostics.Contracts.Internal.ContractHelper.RaiseContractFailedEvent(System.Diagnostics.Contracts.ContractFailureKind,System.String,System.String,System.Exception)
  parent: System.Diagnostics.Contracts.Internal.ContractHelper
  isExternal: false
  name: RaiseContractFailedEvent(ContractFailureKind,String,String,Exception)
  nameWithType: ContractHelper.RaiseContractFailedEvent(ContractFailureKind,String,String,Exception)
  fullName: System.Diagnostics.Contracts.Internal.ContractHelper.RaiseContractFailedEvent(ContractFailureKind,String,String,Exception)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Diagnostics.Contracts.ContractFailureKind
  parent: System.Diagnostics.Contracts
  isExternal: true
  name: ContractFailureKind
  nameWithType: ContractFailureKind
  fullName: System.Diagnostics.Contracts.ContractFailureKind
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Diagnostics.Contracts.Internal.ContractHelper.TriggerFailure(System.Diagnostics.Contracts.ContractFailureKind,System.String,System.String,System.String,System.Exception)
  parent: System.Diagnostics.Contracts.Internal.ContractHelper
  isExternal: false
  name: TriggerFailure(ContractFailureKind,String,String,String,Exception)
  nameWithType: ContractHelper.TriggerFailure(ContractFailureKind,String,String,String,Exception)
  fullName: System.Diagnostics.Contracts.Internal.ContractHelper.TriggerFailure(ContractFailureKind,String,String,String,Exception)
- uid: System.Diagnostics.Contracts.Internal.ContractHelper.RaiseContractFailedEvent*
  parent: System.Diagnostics.Contracts.Internal.ContractHelper
  isExternal: false
  name: RaiseContractFailedEvent
  nameWithType: ContractHelper.RaiseContractFailedEvent
- uid: System.Diagnostics.Contracts.Internal.ContractHelper.TriggerFailure*
  parent: System.Diagnostics.Contracts.Internal.ContractHelper
  isExternal: false
  name: TriggerFailure
  nameWithType: ContractHelper.TriggerFailure
