### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlInternalException
  id: XamlInternalException
  children:
  - System.Xaml.XamlInternalException.#ctor
  - System.Xaml.XamlInternalException.#ctor(System.String)
  - System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: XamlInternalException
  nameWithType: XamlInternalException
  fullName: System.Xaml.XamlInternalException
  type: Class
  summary: "XAML の読み取り中および XAML の書き込み中に発生した内部不整合に対してスローされる例外。"
  remarks: "XAML リーダーまたはライターは XAML システムの一部の側面は、コードによって拡張され、不整合または実装の問題が発生しました .NET Framework XAML サービスのシステム コードに渡された場合にのみ、この例外は通常スローされます。 XAML を解析し、xaml でエラーが発生したなどのサード パーティから発生した例外が XamlInternalException、スローせず、<xref:System.Xaml.XamlParseException>または<xref:System.Xaml.XamlObjectWriterException>。</xref:System.Xaml.XamlObjectWriterException></xref:System.Xaml.XamlParseException>などその他の例外をスローすることが代わりにする必要があります。       .NET Framework XAML サービスを拡張するコードを記述する場合具体的には、XAML リーダーまたは XAML ライターの実装のコードを記述する必要がありますを維持できますこの XamlInternalException と、その他の XAML 関連の例外を区別します。 コードは、クラスの拡張機能をさらに、呼び出し可能なコードを定義するデザインの原則や実装パターンに違反して 場合に XamlInternalException をスローする必要がありますのみです。 コードでは、例外の場合、XAML リーダーまたはライターの XAML 実装拡張子のない使用、サード パーティ製の XAML やサードパーティの XAML スキーマ コンテキストを読み込むために使用には、その他の XAML に固有例外をスローする必要があります。"
  syntax:
    content: 'public class XamlInternalException : System.Xaml.XamlException'
  inheritance:
  - System.Exception
  - System.Xaml.XamlException
  implements: []
  inheritedMembers:
  - System.Xaml.XamlException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Xaml.XamlException.LineNumber
  - System.Xaml.XamlException.LinePosition
  - System.Xaml.XamlException.Message
  platform:
  - net462
- uid: System.Xaml.XamlInternalException.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlInternalException
  langs:
  - csharp
  name: XamlInternalException()
  nameWithType: XamlInternalException.XamlInternalException()
  fullName: System.Xaml.XamlInternalException.XamlInternalException()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Xaml.XamlInternalException&quot;> </xref>エラーを説明するシステム提供のメッセージを持つクラス。"
  syntax:
    content: public XamlInternalException ();
    parameters: []
  overload: System.Xaml.XamlInternalException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlInternalException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Xaml.XamlInternalException
  langs:
  - csharp
  name: XamlInternalException(String)
  nameWithType: XamlInternalException.XamlInternalException(String)
  fullName: System.Xaml.XamlInternalException.XamlInternalException(String)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Xaml.XamlInternalException&quot;> </xref>エラーを説明するメッセージが指定されたクラスです。"
  syntax:
    content: public XamlInternalException (string message);
    parameters:
    - id: message
      type: System.String
      description: "例外を説明するメッセージ。"
  overload: System.Xaml.XamlInternalException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Xaml.XamlInternalException
  langs:
  - csharp
  name: XamlInternalException(SerializationInfo,StreamingContext)
  nameWithType: XamlInternalException.XamlInternalException(SerializationInfo,StreamingContext)
  fullName: System.Xaml.XamlInternalException.XamlInternalException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Xaml.XamlInternalException&quot;> </xref>シリアル化されたデータを持つクラス。"
  syntax:
    content: protected XamlInternalException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "シリアル化されたオブジェクト データを保持するオブジェクト。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "ソースまたは転送先に関する文脈情報。"
  overload: System.Xaml.XamlInternalException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Xaml.XamlInternalException
  langs:
  - csharp
  name: XamlInternalException(String,Exception)
  nameWithType: XamlInternalException.XamlInternalException(String,Exception)
  fullName: System.Xaml.XamlInternalException.XamlInternalException(String,Exception)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Xaml.XamlInternalException&quot;> </xref>指定したエラー メッセージおよびこの例外の原因となった内部例外への参照を持つクラス。"
  syntax:
    content: public XamlInternalException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "例外を説明するメッセージ。"
    - id: innerException
      type: System.Exception
      description: "現在の例外の原因となった例外。 場合、`innerException`パラメーターが<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>で現在の例外が発生、 <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref>ブロックは、内部例外を処理します。"
  overload: System.Xaml.XamlInternalException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlException
  isExternal: false
  name: System.Xaml.XamlException
- uid: System.Xaml.XamlInternalException.#ctor
  parent: System.Xaml.XamlInternalException
  isExternal: false
  name: XamlInternalException()
  nameWithType: XamlInternalException.XamlInternalException()
  fullName: System.Xaml.XamlInternalException.XamlInternalException()
- uid: System.Xaml.XamlInternalException.#ctor(System.String)
  parent: System.Xaml.XamlInternalException
  isExternal: false
  name: XamlInternalException(String)
  nameWithType: XamlInternalException.XamlInternalException(String)
  fullName: System.Xaml.XamlInternalException.XamlInternalException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Xaml.XamlInternalException
  isExternal: false
  name: XamlInternalException(SerializationInfo,StreamingContext)
  nameWithType: XamlInternalException.XamlInternalException(SerializationInfo,StreamingContext)
  fullName: System.Xaml.XamlInternalException.XamlInternalException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)
  parent: System.Xaml.XamlInternalException
  isExternal: false
  name: XamlInternalException(String,Exception)
  nameWithType: XamlInternalException.XamlInternalException(String,Exception)
  fullName: System.Xaml.XamlInternalException.XamlInternalException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Xaml.XamlInternalException.#ctor*
  parent: System.Xaml.XamlInternalException
  isExternal: false
  name: XamlInternalException
  nameWithType: XamlInternalException.XamlInternalException
