### YamlMime:ManagedReference
items:
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  id: ForeignKeyReferenceAlreadyHasValueException
  children:
  - System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor
  - System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String)
  - System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException
  nameWithType: ForeignKeyReferenceAlreadyHasValueException
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  type: Class
  summary: "エンティティが既に読み込まれている場合は、外部キーを変更しようとしましたがときに発生するエラーを表します。"
  syntax:
    content: 'public class ForeignKeyReferenceAlreadyHasValueException : InvalidOperationException'
  inheritance:
  - System.InvalidOperationException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor
  id: '#ctor'
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException()
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException&quot;> </xref>エラーを説明するシステム提供のメッセージを持つクラス。"
  remarks: "このコンス トラクター、 <xref:System.Exception.Message%2A>&quot;DefaultMessageDisplayedByParameterlessCtorWriterMustSupply&quot;など、エラーを説明するシステム提供のメッセージの新しいインスタンスのプロパティ</xref:System.Exception.Message%2A>。 このメッセージでは、現在のシステム カルチャが考慮されます。       次の表は、 <xref:System.InsufficientMemoryException>。</xref:System.InsufficientMemoryException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`.|  |<xref:System.Exception.Message%2A>|ローカライズされたエラー メッセージ文字列 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public ForeignKeyReferenceAlreadyHasValueException ();
    parameters: []
  overload: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException(String)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException&quot;> </xref>エラーを説明するメッセージが指定されたクラスです。"
  remarks: "次の表は、 <xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>。</xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`.|  |<xref:System.Exception.Message%2A>|指定されたエラー メッセージ文字列`message`|</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public ForeignKeyReferenceAlreadyHasValueException (string message);
    parameters:
    - id: message
      type: System.String
      description: "例外を説明するメッセージ。 このコンス トラクターの呼び出し元は、この文字列が現在のシステムのカルチャに合わせてローカライズ済みであることを確認するために必要です。"
  overload: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "新しいインスタンスを初期化、 <xref href=&quot;System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException&quot;> </xref>指定したエラー メッセージおよびこの例外の原因となった内部例外への参照を持つクラス。"
  remarks: "前の例外への参照を含める必要があります前の例外の直接の結果としてスローされる例外、<xref:System.Exception.InnerException%2A>プロパティ</xref:System.Exception.InnerException%2A>。 <xref:System.Exception.InnerException%2A>プロパティは、コンス トラクターに渡されたものと同じ値を返しますまたは`null`場合、<xref:System.Exception.InnerException%2A>プロパティがコンス トラクターには、内部例外値を指定していません</xref:System.Exception.InnerException%2A></xref:System.Exception.InnerException%2A>。       次の表は、 <xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>。</xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>のインスタンスの初期プロパティ値を示しています。      |プロパティ |値 |  |--------------|-----------|  |<xref:System.Exception.InnerException%2A>|`null`.|  |<xref:System.Exception.Message%2A>|指定されたエラー メッセージ文字列`message`|</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A> 。"
  syntax:
    content: public ForeignKeyReferenceAlreadyHasValueException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "例外を説明するメッセージ。 このコンス トラクターの呼び出し元は、この文字列が現在のシステムのカルチャに合わせてローカライズ済みであることを確認するために必要です。"
    - id: innerException
      type: System.Exception
      description: "現在の例外の原因となった例外。 場合、`innerException`パラメーターではありません<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>で現在の例外が発生、 <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref>ブロックは、内部例外を処理します。"
  overload: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.InvalidOperationException
  isExternal: false
  name: System.InvalidOperationException
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException()
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String)
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException(String)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String,System.Exception)
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException
